grafana:
  enabled: true
  adminUser: admin
  adminPassword: gitops123

  service:
    type: LoadBalancer

prometheus:
  prometheusSpec:
    retention: 7d

  service:
    type: LoadBalancer

alertmanager:
  enabled: true
  service:
    type: LoadBalancer

  alertmanagerSpec:
    configSecret: alertmanager-custom-config
