apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-alert
  namespace: monitoring
  labels:
    release: prometheus 
spec:
  groups:
  - name: pod.rules
    rules:
    - alert: PodCrashLooping
      expr: kube_pod_container_status_restarts_total > 5
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod restarting frequently"
        description: "Pod has restarted more than 5 times"