apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring
  labels:
    release: prometheus   # 🔥 MOST IMPORTANT
spec:
  groups:
  - name: test.rules
    rules:
    - alert: AlwaysFiring
      expr: vector(1)
      for: 10s
      labels:
        severity: critical
      annotations:
        summary: "Test Alert"
        description: "This alert always fires"