frontend:
  image:
    repository: 364478544576.dkr.ecr.ap-south-1.amazonaws.com/dev-gitops-repo
    tag: frontend-a286f785af670a0c649d3d69f76a258a43976681

  replicaCount: 1

  service:
    type: ClusterIP
    port: 3000

backend:
  image:
    repository: 364478544576.dkr.ecr.ap-south-1.amazonaws.com/dev-gitops-repo
    tag: backend-a286f785af670a0c649d3d69f76a258a43976681

  replicaCount: 1

  service:
    type: ClusterIP
    port: 5000

database:
  host: dev-employee-db.cl2i66i2usif.ap-south-1.rds.amazonaws.com
  name: employee_db
  port: 5432
  user: postgres
  
autoscaling:
  enabled: false