apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: argo-app=364478544576.dkr.ecr.ap-south-1.amazonaws.com/argo-app
    argocd-image-updater.argoproj.io/argo-app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main

spec:
  project: default
  spec:
  source:
    repoURL: https://github.com/SUNILCHOUHA/cloud-netive-devops-pipeline.git
    targetRevision: main
    path: gitops-repo
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true