apiVersion: apps/v1
kind: Deployment

metadata:
  name: database-deploy 
  namespace: ci-cd

spec:
  replicas: 1
  selector:
    matchLabels:
      app: database

  template:
    metadata:
      labels:
        app: database
    spec: 
      containers:
      - name: database
        image: mysql
        ports:
        - containerPort: 3306
        