apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deploy 
  namespace: ci-cd

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
    spec: 
      containers:
      - name: backend
        image: sunilchouha/notes-app-backend:IMAGE_TAG
        ports:
        - containerPort: 80
        