apiVersion: image.toolkit.fluxcd.io/v1beta2   # Note: FluxCD CRD install karna pad sakta hai (argo-image-updater supports)
kind: ImageUpdateAutomation
metadata:
  name: argo-app-updater
  namespace: argocd
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: argo-app   # tera Application ka source
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: Sunil Chouhan
        email: chouhansunilm@gmail.com
      messageTemplate: "Update image {{range .Updated.Images}}{{.}}{{end}}"
    push:
      branch: main
  update:
    strategy: Setters
    path: ./gitops-repo   # jahan manifests hain