apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-alerts
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  source:
    repoURL: https://github.com/SUNILCHOUHA/cloud-netive-devops-pipeline.git
    targetRevision: main
    path: alerts

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true