name: CD Pipeline 
on:
  workflow_dispatch:
  

jobs:
  argocd:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::364478544576:role/100DaysOfDevOps
          aws-region: ap-south-1

      - name: Login to EKS Cluster
        run: aws eks update-kubeconfig --region ap-south-1 --name dev-gitops-cluster

      - name: Wait for ArgoCD
        run: |
          kubectl wait --for=condition=available deployment/dev-argocd-server -n argocd --timeout=120s

      - name: Verify ArgoCD
        run: kubectl get pods -n argocd 

      - name: Verify ArgoCD Services
        run: kubectl get svc -n argocd 

      - name: Wait for ArgoCD CRDs 
        run: |
          kubectl wait --for condition=established crd/applications.argoproj.io --timeout=180s

      - name: Create Monitoring Namespace
        run: |
          kubectl create namespace monitoring \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create Database Secret
        run: |
          kubectl create secret generic db-secret \
            --from-literal=DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -n default \
            --dry-run=client -o yaml | kubectl apply -f -


      - name: Generate Alertmanager Config
        run: |
          cat > alertmanager.yaml << EOF
          global:
            smtp_smarthost: smtp.gmail.com:587
            smtp_from: sunilchouhanw@gmail.com
            smtp_auth_username: sunilchouhanw@gmail.com
            smtp_auth_password: ${{ secrets.SMTP_PASSWORD }}
            smtp_require_tls: true

          route:
            receiver: gmail-alerts
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 1h


          receivers:
            - name: gmail-alerts
              email_configs:
                - to: sunilchouhanw@gmail.com
                  send_resolved: true

            - name: "null"
          EOF

      - name: Create Alertmanager Secret
        run: |
          kubectl create secret generic alertmanager-config \
            --from-file=alertmanager.yaml=alertmanager.yaml \
            -n monitoring \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy ArgoCD Applications
        working-directory: gitops-k8s/argocd
        run: |
          kubectl apply -f .

      - name: RollOut Prometheus Operator
        run: 
          kubectl rollout restart deployment prometheus-kube-prometheus-operator -n monitoring 

      
      - name: Verify Applications Health
        run: kubectl get applications -n argocd
